#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-01 23:25:34 cf>

case $BLOCK_BUTTON in
	1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) "$TERMINAL" -e htop ;;
	3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) emc "$0" ;;
esac

# used / percent of total
free --mebi | sed -n '2{p;q}' | awk '{printf ("%.1f (%d%%)\n", ($3 / 1024), ($3 / $2) * 100)}'

# used / total
#free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.1f/%2.1f\n", ( $3 / 1024), ($2 / 1024))}'

#percentage of total used
# free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2f%%\n", ($3 / $2) * 100)}'
