#!/bin/sh
#             _                                            _   
#   __ _  ___| |_ ___ ___  _ __ ___  _ __  _ __ ___   ___ | |_ 
#  / _` |/ _ \ __/ __/ _ \| '_ ` _ \| '_ \| '__/ _ \ / _ \| __|
# | (_| |  __/ || (_| (_) | | | | | | |_) | | | (_) | (_) | |_ 
#  \__, |\___|\__\___\___/|_| |_| |_| .__/|_|  \___/ \___/ \__|
#  |___/                            |_|                        
#  
# A helper script for LaTeX/groff files used by `compiler` and `opout`.
# The user can add the root file of a larger project as a comment as below:
# % root = mainfile.tex
# And the compiler script will run on that instead of the opened file.

texroot="$(sed -n 's/^\s*%.*root\s*=\s*\(\S\+\).*/\1/p' "${1}")"
[ -f "${texroot}" ] && readlink -f "${texroot}" || exit "1"
