#!/bin/zsh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:
# Time-stamp: <2025-08-09 01:42:19 cf>
# Box: cf [Linux 6.15.8-zen1-1-zen x86_64 GNU/Linux]

# Ever pasted "$ somecommand" into the terminal and gotten this error?
# -bash: $: command not found

# Begone, silly errors! Lazy copy + paste forever!! ETCETERA!!!!
echo 'Quit pasting in commands from the internet, you lazy bum.'
"$@"
