#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-03 13:32:58 cf>

# keybind to renew dwm sending the currently active window to tag 1.
# TODO: Patch dwm for preserving layouts, sizes and tags.
xdotool key super+shift+1

export WM="dwm"

case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

# # This function is needed if there are multiple instances of the window manager.
# wmpid(){
# 	tree="$(pstree -ps $$)"
# 	tree="${tree#*$WM(}"
# 	echo "${tree%%)*}"
# }
# kill -HUP "$(wmpid)"

kill -HUP "$(pidof "$WM")"
