#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:

MPVSESH="$HOME/Videos/playlists/mpvmux-sessions"
[ -d "$(dirname "$MPVSESH")" ] || mkdir -p "$(dirname "$MPVSESH")"
[ -f "$MPVSESH" ] || touch "$MPVSESH"

muxmpv() {
    tmux list-windows -t mpv | sed 's/[-*]$//;s/#$//;s/^ //;s/ $//' >"$MPVSESH"
    [ -f "$MPVSESH" ] && [ "$(grep -c . "$MPVSESH")" -gt 0 ] || { echo "No current mpvmux sessions." ; return 1 ; }
    select="$(tmux list-windows -t mpv | awk '{print $2}' | sed 's/[-*]$//;s/#$//;s/^ //;s/ $//' | fzf)"
    tmux switch-client -t mpv:"$select" || tmux attach -t mpv:"$select" || return 1 ;
    return 0
}

usage() {
    env SC=${0##*/} envsubst <<-'MAN'
    Usage: ${SC} <media_input>
MAN
}

extinfpipe() {
    exifjpg -gtu "$1" | {
    read -r d ; read -r t ; read -r u ;
    s=$(echo "$d" | awk -F: 'NF==3 {print $1*3600+$2*60+$3}; NF==2 {print $1*60+$2}; NF==1 {print $1}')
    printf "#EXTINF:%s,%s\n%s\n" "$s" "$t" "$u"
  }
}

has_hls_header() { sed -n "1p" "$1" | grep -q "^#EXTM3U" || sed -i "1i #EXTM3U" "$1" ; }
timestamp_format() {
  in="$1"
  out=${2:-timestamps}
  [ -f "$in" ] || { echo "File not found" >&2; return 1 ; }
  while read -r l; do
    t=$(echo "$l" | cut -d' ' -f1 | awk -F: '{
      if (NF == 3) printf "%02d:%02d:%02d", $1, $2, $3;
      else if (NF == 2) printf "00:%02d:%02d", $1, $2;
      else if (NF == 1) printf "00:00:%02d", $1;
    }')
    c=$(echo "$l" | cut -d' ' -f2-)
    printf "%s\t%s\n" "$t" "$c"
  done < "$in" > "$out"
  tail "$out"
}

append_extinf() {
    i="$1"
    [ -L "$i" ] && f=$(readlink -f "$i") || f=$(realpath "$i")
    if [ -f "$f" ]; then
        case $(file --dereference --brief --mime-type "$f") in
            video/*|audio/*)
                if [ ${f##*.} = "m3u8" ]; then
                    [ "$(head -n 1 "$u")" = "#EXTM3U" ] || sed -i "1i #EXTM3U" "$u"
                    u=$(grep -vE '^#EXTM3U' "$f")
                else
                    f="$1"
                    r=$(realpath "$f")
                    n=$(basename "$r"| sed "s/^.\///;s/\\\//g")
                    d=$(mediainfo --INFORM="Video;%Duration%" "$f" | cut -d. -f1)
                    s=$((d/1000))
                    t=${n%.*}
                    u=$(printf "#EXTINF:%s,%s\n%s\n" "$s" "$t" "$r")
                fi
                ;;
            image/jpeg)
                u=$(exifjpg -M "$i" 2>/dev/null) || u=$(printf '#EXINF:0,%s,%s\n%s\n' "${f##*/}" "$(date -d "$(stat -L "$f" -c "%w")" +%F)" "$f") ;;
        esac
    else
        ytln "$u" | while read -r url ; do
            u=$(exifjpg -M "$u")
        done
    fi
    [ -n "$u" ] && echo "$u" || return 1
    return 0
}

tmpfile=$(mktemp --suffix=".m3u8")
echo "#EXTM3U" > "$tmpfile"

for f in "$@" ; do
    append_extinf "$f" 2>/dev/null | tee -a "$tmpfile"
done

tmux has-session -t mpv >/dev/null 2>&1 || tmux new-session -d -s "mpv"

[ -n "$n" ] || n="yt"
if tmux new-window -t mpv: -n "$n" -- "mpv -quiet ${tmpfile} 2>&1" ; then
    echo "tmux attach -t mpv:${n}" | tee -a "$MPVSESH"
    exit 0
else
    muxmpv || exit 1
fi

exit 0
