#!/bin/sh

json_file="$1"
image_file="$2"

[ $# -ne 2 ] && echo "Usage: embedjson <json_file> <image_file>" && exit 1
[ "${image_file##*.}" = "json" ] && [ "$(file --dereference --brief --mime-type "$json_file")" = "image/*" ] && \
    { image_file="$json_file" ; json_file="$image_file" ; }

json_data=$(jq '.' -r "$json_file")

# Embed the JSON data as EXIF UserComment in the image
if exiftool -overwrite_original -UserComment="$json_data" "$image_file"; then
    echo "JSON successfully embedded into $image_file."
    rm "$json_file"
else
    echo "Failed to embed JSON into $image_file."
fi

exit 0
