#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-05 02:47:27 cf>

f="$1"
h=$(printf 'Date\tTitle\tDuration\tUri\tThumbnail\n')
[ -f "$f" ] || echo "$h" > "$f" ; [ "$(head -n 1 "$f")" = "$h" ] || sed -i "1i ${h}" "$f"
