#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-05 02:46:46 cf>


f="$1"
[ -L "$f" ] && f=$(readlink -f "$f") || f=$(realpath "$f")
exifjpg -S "\t" -Dtgu $f
printf '\t%s\n' "$f"
