#!/bin/sh
# nsxiv to hls playlist

[ -z "$1" ] && echo "usage: xiv2hls regex 2>&1" && exit 1
base="$(basename "$1")"
[ -L "$1" ] && dirname=$(dirname "$(readlink -f "$1")") || dirname="$(dirname "$1")"
find "$dirname" -maxdepth 1 -type f | awk -v BASE="$base" 'BEGIN { lines = ""; m = 0; } { if ($0 == BASE) { m = 1; } } { if (!m) { if (lines) { lines = lines"\n"; } lines = lines""$0; } else { print $0; } } END { print lines; }' | nsxiv -tio | xargs -0 -I {} exifjpg -M "{}"
