#!/bin/sh
# Alternative to window swallowing - hides the initiating window while executing application.

COMMAND="$*"
BINARY="$(printf "$COMMAND" | sed 's/ .*//')"
ARGS="$(printf "$COMMAND" | sed "s/$BINARY //")"

main() {
	WINID=$(xdo id)
	xdo hide "$WINID"
	$BINARY "$ARGS" || $BINARY "$ARGS"
	xdo show "$WINID"
}

[ "$1" = "" ] && printf "Error: You must provide at least one argument.\nExample usage: xdoswl mpv ~/videos/AmericanPsycho.mkv\n" || main "$@"
