#!/bin/sh

# $1 is a url; $2 is a command
[ -z "$1" ] && { notify-send "pas d'URL icitte.."; exit 1; }
base="$(ytln "$1")"
notify-send "⏳c'dans'queue: $base..."
cmd="$2"
[ -z "$cmd" ] && cmd=$(yt-dlp --embed-metadata -ic)
idnum="$(tsp "$cmd" "$1")"
realname="$(echo "$base" | sed "s/?\(source\|dest\).*//;s/%20/ /g")"
tsp -D "$idnum" mv "$base" "$realname"
tsp -D "$idnum" notify-send "👍 $realname c'gud."
