#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:
# Time-stamp: <2025-07-30 10:16:35 cf>
# Box: cf [Linux 6.15.6-zen1-1-zen x86_64 GNU/Linux]

# URL: https://github.com/vparnas/automations/blob/master/tmux_reinit

CFG_FILE="$HOME/.tmux_sessions"
[ -f "$CFG_FILE" ] || (echo "$CFG_FILE not found" && exit)

# Create or attach to the named session if exists
tmux new-session -s main -d >/dev/null 2>&1

sed '/^\s*#/d' "$CFG_FILE" |
while read -r win_name win_dir command; do
    win_dir=$(eval echo "$win_dir") # allows evaluating '~' or $HOME
    tmux select-window -t "$win_name" >/dev/null 2>&1 ||
        tmux new-window -c "$win_dir" -n "$win_name" \; \
        send-keys "$command" C-m
done

[ -z "$TMUX" ] && tmux attach-session -t main
