#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:
# Time-stamp: <2025-08-07 14:54:21 cf>
# Box: cf [Linux 6.15.8-zen1-1-zen x86_64 GNU/Linux]

# Appends links from selected thumbnails embeded data to mpv socket and playlistfile.
MPVQ_PLAYLIST="$HOME/.cache/mpvq/mpvq.m3u8"
MPVQ_TITLES="$HOME/.cache/mpvq/mpvq.titles"
MPV_SOCK="/tmp/mpv.sock"
PLAYLIST="$HOME/Videos/playlists/adhoc/playlist_$(date +"%F_%H%M").m3u8"

[ ! -f "$MPVQ_TITLES" ] && touch "$MPVQ_TITLES"
[ ! -f "$MPVQ_PLAYLIST" ] && echo "#EXTM3U" > "$MPVQ_PLAYLIST"

export MPVQ_TITLES
export MPVQ_PLAYLIST

# Function to append links to mpv via its socket
to_mpv_sock() {
    f="$1"
    if [ ! -S "$MPV_SOCK" ] || [ ! -w "$MPV_SOCK" ]; then
        echo "Error: MPV socket is missing or not writable." >&2
        return 1
    fi
    grep -E "^http*" "$f" | while read -r url ; do
        echo '{"command": ["loadfile", "'"$url"'", "append"]}' | socat - "$MPV_SOCK" || {
            echo "Warning: Failed to send $url to mpv." >&2
            continue
        }
    done || return 1
    return 0
}

# Find and display all embedded linked thumbnails in custom fzf previewer, pipe selection to both mpvq playlist and tmp playlist.
find "$HOME/Videos/yt" -type l -print0 | uefzf | xargs -0 -I{} exifjpg -M "{}" 2>/dev/null | tee -a  "$MPVQ_PLAYLIST" > "$PLAYLIST"
grep -E '#EXTINF' "$MPVQ_PLAYLIST" | sed "s/\(^#EXTINF:[^,]*,\)\(.*\)\(,[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)/\2/"  > "$MPVQ_TITLES" || {
    echo "Error: Failed to update playlist titles." >&2 ;
    exit 1
}


if ! pkill -RTMIN+15 "${STATUSBAR:-dwmblocks}" ; then
    blockspid=$( ps "$(pgrep dwmblocks)" | grep "${GPG_TTY##*/}" | awk '{print $1}' )
    kill -49 $blockspid || true
fi

[ -t 1 ] && xdo hide "$WINDOWID" || true

MPV_SOCK_W=0
[ -S "$MPV_SOCK" ] || { rm -f "$MPV_SOCK" ; mkfifo "$MPV_SOCK" ; }

# Check if mpv is running and socket is valid before attempting communication
if echo '{"command": ["get_property", "media-title"]}' | socat - "$MPV_SOCK" 2>/dev/null ; then
    MPV_SOCK_W=1
else
    rm -f "$MPV_SOCK" && mkfifo "$MPV_SOCK"
    if echo '{"command": ["get_property", "media-title"]}' | socat - "$MPV_SOCK" 2>/dev/null ; then
        MPV_SOCK_W=1
    else
        echo "error with mpv socket" >&2
        MPV_SOCK_W=0
    fi
fi
if [ $MPV_SOCK_W -gt 0 ] ; then
    if to_mpv_sock "$PLAYLIST" ; then
        rm -f "$PLAYLIST"
        exit 0
    else
        [ "$(head -n 1 "$PLAYLIST")" = "#EXTM3U" ] || sed -i "1i #EXTM3U" "$PLAYLIST"
        echo "Falling back to linkhandler due to mpv socket error." >&2
        linkhandler "$PLAYLIST" || linkhandler "$MPVQ_PLAYLIST" || exit 1
    fi
fi

[ -t 1 ] && xdo show "$WINDOWID" || true

exit 0
