#!/bin/bash

SOURCE="$HOME/Videos/yt/meta"

YTCHANS=(
# "https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA"
# "https://www.youtube.com/channel/UCrqM0Ym_NbK1fqeQG2VIohg"
# "https://www.youtube.com/channel/UCd3dNckv1Za2coSaHGHl5aA"
# "https://www.youtube.com/channel/UC8ENHE5xdFSwx71u3fDH5Xw"
# "https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A"
# "https://www.youtube.com/channel/UCMc1GFSONeLSKvXuHx_N51A"
# "https://www.youtube.com/channel/UCNzszbnvQeFzObW0ghk0Ckw"
# "https://www.youtube.com/channel/UCS97tchJDq17Qms3cux8wcA"
# "https://www.youtube.com/channel/UCkf4VIqu3Acnfzuk3kRIFwA"
# "https://www.youtube.com/channel/UCVls1GmFKf6WlTraIb_IaJg"
# "https://www.youtube.com/channel/UCrUL8K81R4VBzm-KOYwrcxQ"
# "https://www.youtube.com/channel/UC05XpvbHZUQOfA6xk4dlmcw"
# "https://www.youtube.com/channel/UC7YOGHUfC1Tb6E4pudI9STA"
# "https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw"
# "https://www.youtube.com/channel/UCP7WmQ_U4GB3K51Od9QvM0w"
# "https://www.youtube.com/channel/UCqHR0icKT20KwFDjaZuFt7w"
# "https://www.youtube.com/channel/UCngn7SVujlvskHRvRKc1cTw"
# "https://www.youtube.com/channel/UCg6gPGh8HU2U01vaFCAsvmQ"
# "https://www.youtube.com/channel/UCylGUf9BvQooEFjgdNudoQg"
# "https://www.youtube.com/channel/UCSckp-N4zP4V8GnZGxVqjTg"
# "https://www.youtube.com/channel/UCKhVag9OGIOJu_x430Dmedw"
# "https://www.youtube.com/channel/UCxwcmRAmBRzZMNS37dCgmHA"
# "https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA"
## "https://www.youtube.com/channel/UCSsHJShN9qNXqXD1j2emaqg"
  # "https://www.youtube.com/channel/UCbRP3c757lWg9M-U7TyEkXA"
  # "https://www.youtube.com/channel/UC1Zfv1Zrp1q5lKgBomzOyCA"
  # "https://www.youtube.com/channel/UClxaaAzHu1B5EoTtBYea7ig"
  # "https://www.youtube.com/channel/UCVBA7-PfzHIkfPfZ3UiqWdg"
  # "https://www.youtube.com/channel/UCi8BnqbhQripV0V-gqx7oEg"
  # "https://www.youtube.com/channel/UCAi6GKtTPoYxUheIbVhnwqw"
  # "https://www.youtube.com/channel/UC4w1YQAJMWOz4qtxinq55LQ"
  # "https://www.youtube.com/channel/UCSiPjfAJBgbFlIUsxOWpK0w"
  # "https://www.youtube.com/channel/UC-2JUs_G21BrJ0efehwGkUw"
  # "https://www.youtube.com/channel/UCJs0hk9Ib9stBmiBdvG2zkQ"
  # "https://www.youtube.com/channel/UCRBpynZV0b7ww2XMCfC17qg"
  # "https://www.youtube.com/channel/UCyFWoLmPTgZ3BkHIKMRSV1g"
  # "https://www.youtube.com/channel/UCHASrbCS-niYRn-Y3WX38pA"
  # "https://www.youtube.com/channel/UCIALMKvObZNtJ6AmdCLP7Lg"
  # "https://www.youtube.com/channel/UCi8C7TNs2ohrc6hnRQ5Sn2w"
  # "https://www.youtube.com/channel/UC4SVo0Ue36XCfOyb5Lh1viQ"
  # "https://www.youtube.com/channel/UCgKzdfWnTie2OD4bfaZKaQw"
  # "https://www.youtube.com/channel/UCvISIg_p5A19MzavYSojNyw"
  # "https://www.youtube.com/channel/UCuFFtHWoLl5fauMMD5Ww2jA"
  # "https://www.youtube.com/channel/UClcE-kVhqyiHCcjYwcpfj9w"
  # "https://www.youtube.com/channel/UCrjKdwxaQMSV_NDywgKXVmw"
  # "https://www.youtube.com/channel/UCR-DXc1voovS8nhAvccRZhg"
  # "https://www.youtube.com/channel/UC9x0AN7BWHpCDHSm9NiJFJQ"
  # "https://www.youtube.com/channel/UCnsj4TU7mOQ-4l2HOaRekgA"
  # "https://www.youtube.com/channel/UCWPJwoVXJhv0-ucr3pUs1dA"
  # "https://www.youtube.com/channel/UCWF0PiUvUi3Jma2oFgaiX2w"
  # "https://www.youtube.com/channel/UCxAICW_LdkfFYwTqTHHE0vg"
  # "https://www.youtube.com/channel/UCDiKw3GnFIwyNJBzhCoRI-Q"
  # "https://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA"
  # "https://www.youtube.com/channel/UC1xaOCNeVbO9q9cnoCA-XaA"
  # "https://www.youtube.com/channel/UCjgpFI5dU-D1-kh9H1muoxQ"
  # "https://www.youtube.com/channel/UCvOOv9tfBMSzcXnDkgzMufA"
  # "https://www.youtube.com/channel/UC3I2GFN_F8WudD_2jUZbojA"
  # "https://www.youtube.com/channel/UCcmw3P6BDUFA4h3Y_FpsB_w"
  # "https://www.youtube.com/channel/UCoS8kP28lY4mkjOt5Znv9LA"
  # "https://www.youtube.com/channel/UC-V8FVQCUpRRUPNClviki3w"
)

# count=1
# for c in "${YTCHANS[@]}"; do
#   ytdlp "$c"
#   notify-send "Metadata Import" "[ $count / ${#YTCHANS[@]} ]"
#   count=$((count+1))
# done

# jsonfmt() {
#   d=${1:-$(pwd)}
#   tmp=$(mktemp -d)
#   for f in *.json; do
#     jq . "$f" > "$tmp/$f" && mv "$tmp/$f" "$d" -f
#   done && rm -rf "$tmp" && echo "$d jsons formatted."
# }

src_dirs=$(find "$SOURCE" -type d)
srccnt="${#src_dirs}"
# for dir in $src_dirs; do
#     jsonfmt "$dir"
# done

count=1
for dir in "${src_dirs[@]}"; do
     add_json_descriptions "$dir" && notify-send "Metadata Import [ $count / $srccnt ]"
     count=$((count+1))
done

echo "Importing metadata to database..."
notify-send "Importing metadata to database..."
mpvq_dbimport

exit 0
