#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:

set -e

psel=$(xclip -selection primary -o 2>/dev/null)
adir="$HOME/.local/keys/regs"
areg="$adir/a"

[ -d "$adir" ] || mkdir -p "$adir"
[ -n "$psel" ] || { echo "no primary selection" >&2 ; exit 1 ; }

if command -v notify-send >/dev/null 2>&1 ; then
    notify-send "[ KP0 primary to a clipregister ]"
    echo "$psel" > "$areg" ; acat=$(cat "$areg")
    notify-send "a: $acat" && echo "" | xclip -in -selection primary
fi
