#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:

set -e

psel=$(xclip -selection primary -o 2>/dev/null)

[ -n "$psel" ] || { echo "no primary selection" >&2 ; exit 1 ; }

csel=$(xclip -selection clipboard -o 2>/dev/null)

echo "$psel" | xclip -in -selection clipboard

if command -v notify-send >/dev/null 2>&1 ; then
  [ "$psel" = "$csel" ] && notify-send "[ KP3 primary to clipboard ]" "$csel"
fi
