#!/bin/sh
# -*- mode: sh; sh-shell: sh; -*- vim: ft=sh:ts=2:sw=2:et:

set -e

psel=$(xclip -selection primary -o 2>/dev/null)

[ -n "$psel" ] || { echo "no primary selection" >&2 ; exit 1 ; }

if command -v notify-send >/dev/null 2>&1 ; then
    notify-send "[ KP5 Primary Selection ]" "$psel"
fi
