#!/bin/bash
# fzf ueberzug preview for mpvqfzf

set -e

cleanup() {
    exec 3>&-
    rm "$FIFO_UEBERZUG"
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	fzf --multi --preview "$@" --preview-window=right:50%:wrap
	fzf --read0 --reverse --delimiter='/' --with-nth=6,7 --multi --preview "uescope {}" "$@" --height=100% --preview-window=right:44%:56%:wrap:sharp --padding=0 --ansi --print0 3>&-
else
	[ ! -d "$HOME/.cache/lf" ] && mkdir -p "$HOME/.cache/lf"
	export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup HUP INT QUIT TERM PWR EXIT

	fzf --read0 --reverse --delimiter='/' --with-nth=6,7 --multi \
		--preview 'echo {} | cut -d"/" -f6,7 | tr "/" "\t" && uescope {}' \
		--height=100% --preview-window=top:35%:65%:wrap:sharp --padding=0 --print0 3>&-
fi
