#!/bin/sh
# -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
# Time-stamp: <2025-07-27 19:29:41 cf>
# Box: cf [Linux 6.15.6-zen1-1-zen x86_64 GNU/Linux]

echo 'PS %CPU %MEM VSZ RSS' > ~/psls

ps=(dwm ffmpeg mpv tmux nvim qutebrowser)

for p in $ps; do
	ps aux | grep "$p" | awk '!/grep/' | awk '{print $11, $3, $4, $5, $6}' >> ~/psls
done

cat ~/psls | piper -m fr_FR-gilles-low 100 'comment optimiser les ressources utilisées'

exit 0
