#!/bin/sh

ffmpeg -f x11grab -s 1680x1050 -i :0.0+6496,0 -fflags nobuffer -flags low_delay -probesize 32 -f v4l2 /dev/video3 &
ffmpeg_pid=$!

sleep 1 

cleanup() {
    echo "Cleaning up..."
    kill $ffmpeg_pid
}

trap cleanup EXIT

mpv av://v4l2:/dev/video3 --no-cache --profile=low-latency --untimed --no-demuxer-thread --vd-lavc-threads=1 --title="DisplayPort-0"

